name = "jetbrains"
inherits = "jetbrains_dark"

# Custom colors
# --------------
# class, module, namespace names
# namespace = "teal"
# type = "teal"

attribute = "yellow"
tag = "teal"
type = "teal"
function = "blue"
constructor = "whte"
"variable.other" = "teal"
# "keyword.storage.type" = "yellow"

# tabs
"ui.bufferline" = { fg = "blue196", bg = "blue34" }
"ui.bufferline.active" = { fg = "teal" }

[palette]
blue = "#57A8F5"
teal = "#70AFBD"
yellow = "#FFC97F"
white = "#FFFFFF"
